### PR TITLE
Refactor validate_* modules

### PR DESCRIPTION
**Pull request by abikouo**

### CODE REVIEW

**Comment by jillr** [comment]
@abikouo Why are we refactoring these modules?  Is this PR related to a ticket or lint failure?  If it is still needed can you please resolve the git conflicts and ask the team for reviews?

**Comment by gravesm** [comment]
@abikouo Could you respond to @jillr's feedback, or close the issue?

**Comment by abikouo** [comment]
> @abikouo Why are we refactoring these modules? Is this PR related to a ticket or lint failure? If it is still needed can you please resolve the git conflicts and ask the team for reviews?

At the time I was writing a blog post related to these modules, I discovered a lot of issues while trying to validate these modules. This is a way to fix those issues.
I will update the pull request description and resolve merge conflicts

**Comment by jillr** [comment]
@abikouo can you please update this PR and request reviews or can it be closed?

**Comment by abikouo** [comment]
> @abikouo can you please update this PR and request reviews or can it be closed?

@jillr It can be closed.

**Pull request closed without merging**
